suivi:
    resource: "@SuiviBundle/Resources/config/routing.yml"
    prefix:   /

etablissement:
    resource: "@EtablissementBundle/Resources/config/routing.yml"
    prefix:   /

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /Article

ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /

forum:
    resource: "@ForumBundle/Resources/config/routing.yml"
    prefix:   /

gu:
    resource: "@GUBundle/Resources/config/routing.yml"
    prefix:   /
kms_froala_editor:
  resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
  prefix:   /article

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"